CREATE TABLE IF NOT EXISTS exchange_rates (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    base VARCHAR(3) NOT NULL,
    USD NUMERIC(10, 6) NOT NULL,
    GBP NUMERIC(10, 6) NOT NULL,
    EUR NUMERIC(10, 6) NOT NULL
);
